### ISSUE TITLE
Create an awesome ruby community

### ISSUE THREAD

**Issue by kathgironpe** [Sdogruyol/awesome-ruby#43]
Hello @Sdogruyol . 

I want to contribute more but I am confused. 

Why are there two awesome-ruby repos?

https://github.com/markets/awesome-ruby

Have you tried to chat with @markets and discussed possibility of merging changes for both repos into just one?

**Comment by daluu** [comment]
FYI, I noticed this one as well: https://github.com/uhub/awesome-ruby
